packages:
  - '.'

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - msgpackr-extract
  - onnxruntime-node
  - protobufjs
  - sharp
patchedDependencies:
  '@protontech/crypto@2.1.3': patches/@protontech__crypto@2.1.3.patch
