import { afterEach, describe, expect, test, vi } from 'vitest'
import { tagAutocomplete } from './action'
import { normalizeTagAutocompleteSettings } from './settings'

const results = [{ word: 'blue hair', category: 0, frequency: 200, redirect: 'null' },
    { word: '푸른 머리', category: 0, frequency: 100, redirect: 'blue hair' }]
const search = vi.fn(async (_query: string, _signal?: AbortSignal) => results)
vi.mock('./client', () => ({ searchTags: (query: string, signal?: AbortSignal) => search(query, signal) }))
let cleanup: (() => void)[] = []
function mount(text = '', settings = normalizeTagAutocompleteSettings()) {
    const input = document.createElement('textarea')
    input.value = text
    document.body.append(input)
    const action = tagAutocomplete(input, settings)
    cleanup.push(action.destroy)
    input.focus()
    return { input, action }
}
async function edit(input: HTMLTextAreaElement, text: string, position = text.length) {
    input.value = text
    input.setSelectionRange(position, position)
    input.dispatchEvent(new InputEvent('input', { bubbles: true, data: text.at(-1) }))
    await settle()
}
async function settle() { await new Promise(resolve => setTimeout(resolve, 0)) }
function key(input: HTMLTextAreaElement, key: string, init: KeyboardEventInit = {}) {
    const event = new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, ...init })
    input.dispatchEvent(event)
    return event
}
afterEach(() => { cleanup.forEach(fn => fn()); cleanup = []; document.body.replaceChildren(); search.mockReset().mockResolvedValue(results) })

describe('per-editor tag autocomplete', () => {
    test('cycles and confirms Enter/Tab without forwarding handled keys', async () => {
        const { input } = mount()
        const outer = vi.fn()
        document.body.addEventListener('keydown', outer)
        await edit(input, 'blu')
        expect(input.getAttribute('aria-controls')).toBe(document.querySelector('[role=listbox]')?.id)
        key(input, 'ArrowUp')
        expect(document.querySelector('[aria-selected=true]')?.textContent).toContain('푸른 머리')
        key(input, 'ArrowDown')
        expect(document.querySelector('[aria-selected=true]')?.textContent).toContain('blue hair')
        expect(key(input, 'Enter').defaultPrevented).toBe(true)
        expect(input.value).toBe('blue hair')
        expect(document.querySelector('[role=listbox]')).toBeNull()
        expect(document.activeElement).toBe(input)
        expect(outer).not.toHaveBeenCalled()
        await edit(input, 'blu')
        key(input, 'ArrowUp')
        key(input, 'Tab')
        expect(input.value).toBe('blue hair')
        document.body.removeEventListener('keydown', outer)
    })
    test('preserves unconfigured modifiers, closed/no-result editing and navigation', async () => {
        const { input } = mount()
        expect(key(input, 'Tab').defaultPrevented).toBe(false)
        await edit(input, 'blu')
        expect(key(input, 'Enter', { ctrlKey: true }).defaultPrevented).toBe(false)
        expect(key(input, 'ArrowDown', { shiftKey: true }).defaultPrevented).toBe(false)
        expect(document.querySelector('[role=listbox]')).toBeNull()
        search.mockResolvedValue([])
        await edit(input, 'zzzz')
        expect(key(input, 'Enter').defaultPrevented).toBe(false)
    })
    test('does not reopen dismissed pending searches; only subsequent input searches again', async () => {
        let finish!: (value: typeof results) => void
        search.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
        const { input } = mount()
        await edit(input, 'blu')
        key(input, 'Escape')
        finish(results)
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
        await edit(input, 'blue')
        expect(document.querySelector('[role=listbox]')).not.toBeNull()
        key(input, 'Escape')
        expect(input.value).toBe('blue')
    })
    test('invalidates stale results on edits, selection, blur and destruction', async () => {
        const pending: ((value: typeof results) => void)[] = []
        search.mockImplementation(() => new Promise(resolve => pending.push(resolve)))
        const { input, action } = mount()
        await edit(input, 'b')
        await edit(input, 'bl')
        pending[0](results)
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
        input.setSelectionRange(0, 0)
        document.dispatchEvent(new Event('selectionchange'))
        pending[1](results)
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
        await edit(input, 'blu')
        input.blur()
        pending[2](results)
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
        input.focus()
        await edit(input, 'blue')
        action.destroy()
        pending[3](results)
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
    })
    test('space closes normally, then multiword input resumes; minimum updates live', async () => {
        const { input, action } = mount()
        await edit(input, 'blue')
        expect(key(input, ' ').defaultPrevented).toBe(false)
        await edit(input, 'blue ')
        expect(document.querySelector('[role=listbox]')).toBeNull()
        await edit(input, 'blue h')
        expect(search).toHaveBeenLastCalledWith('blue h', expect.any(AbortSignal))
        action.update(normalizeTagAutocompleteSettings({ minLength: 10 }))
        await settle()
        expect(document.querySelector('[role=listbox]')).toBeNull()
    })
    test('IME keys reach native editor but never parent handlers or tag selection', async () => {
        const { input } = mount()
        await edit(input, 'blue')
        input.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
        const parent = vi.fn()
        document.body.addEventListener('keydown', parent)
        for (const name of ['Enter', 'ArrowDown', 'Escape']) expect(key(input, name, { isComposing: true }).defaultPrevented).toBe(false)
        input.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true }))
        expect(key(input, 'Enter').defaultPrevented).toBe(false)
        expect(parent).not.toHaveBeenCalled()
        expect(input.value).toBe('blue')
        document.body.removeEventListener('keydown', parent)
    })
    test('pointer choice survives blur ordering, outside click dismisses, editors are isolated', async () => {
        const { input } = mount()
        await edit(input, 'blu')
        const option = document.querySelector('[role=option]')!
        const down = new PointerEvent('pointerdown', { bubbles: true, cancelable: true })
        option.dispatchEvent(down)
        expect(down.defaultPrevented).toBe(true)
        option.dispatchEvent(new MouseEvent('click', { bubbles: true }))
        expect(input.value).toBe('blue hair')
        await edit(input, 'blu')
        document.body.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }))
        expect(document.querySelector('[role=listbox]')).toBeNull()
        const other = mount().input
        await edit(other, 'ha')
        expect(input.getAttribute('aria-expanded')).toBe('false')
        expect(other.getAttribute('aria-expanded')).toBe('true')
    })
    test('replacement preserves weights, right side, caret and one-step fallback undo/redo', async () => {
        const { input, action } = mount('first, 1.2::blu tail::, last')
        await edit(input, input.value, 15)
        key(input, 'Enter')
        expect(input.value).toBe('first, 1.2::blue hair tail::, last')
        expect(input.selectionStart).toBe(21)
        key(input, 'z', { ctrlKey: true })
        expect(input.value).toBe('first, 1.2::blu tail::, last')
        key(input, 'y', { ctrlKey: true })
        expect(input.value).toBe('first, 1.2::blue hair tail::, last')
        action.update(normalizeTagAutocompleteSettings({ scope: 'whole' }))
        await edit(input, 'first, 1.2::blu tail::, last', 15)
        key(input, 'Tab')
        expect(input.value).toBe('first, 1.2::blue hair::, last')
    })
    test('only configured custom shortcuts consume keys and load failure leaves editing intact', async () => {
        const settings = normalizeTagAutocompleteSettings()
        settings.hotkeys.accept = [{ key: 'j', ctrl: true, action: 'accept' }]
        const { input } = mount('', settings)
        await edit(input, 'blu')
        expect(key(input, 'Enter').defaultPrevented).toBe(false)
        expect(key(input, 'j', { ctrlKey: true }).defaultPrevented).toBe(true)
        expect(input.value).toBe('blue hair')
        search.mockRejectedValueOnce(new Error('failed'))
        await edit(input, 'x')
        expect(key(input, 'Enter').defaultPrevented).toBe(false)
    })
    test('IME Enter protection expires after composition commit', async () => {
        const { input } = mount()
        await edit(input, 'blue')
        input.dispatchEvent(new CompositionEvent('compositionstart'))
        input.dispatchEvent(new CompositionEvent('compositionend'))
        await new Promise(resolve => setTimeout(resolve, 70))
        expect(key(input, 'Enter').defaultPrevented).toBe(true)
        expect(input.value).toBe('blue hair')
    })
    test('custom candidate binding takes priority over fallback history', async () => {
        const { input, action } = mount()
        await edit(input, 'blu')
        key(input, 'Enter')
        const settings = normalizeTagAutocompleteSettings()
        settings.hotkeys.accept = [{ key: 'z', ctrl: true, action: 'accept' }]
        action.update(settings)
        search.mockResolvedValue([{ word: 'blue eyes', category: 0, frequency: 10, redirect: 'null' }])
        await edit(input, 'blue h')
        key(input, 'z', { ctrlKey: true })
        expect(input.value).toBe('blue eyes')
    })
})
