import { afterEach, describe, expect, it, vi } from 'vitest'
import { zlibSync } from 'fflate'
import crc32 from 'crc/crc32'
import { compressPainterImage } from './image'
import { preparePainterPng, muxPainterWebp, readPainterImageMetadata } from './metadata'

const text = (value: string) => new TextEncoder().encode(value)
const join = (...parts: Uint8Array[]) => new Uint8Array(parts.flatMap((part) => [...part]))
const read32 = (bytes: Uint8Array, offset: number) => new DataView(bytes.buffer, bytes.byteOffset).getUint32(offset, true)

function pngChunk(name: string, data: Uint8Array) {
    const out = new Uint8Array(data.length + 12)
    const view = new DataView(out.buffer)
    view.setUint32(0, data.length)
    out.set(text(name), 4)
    out.set(data, 8)
    view.setUint32(data.length + 8, crc32(Buffer.from(out.subarray(4, data.length + 8))))
    return out
}

function png(...metadata: Uint8Array[]) {
    const ihdr = new Uint8Array(13)
    const view = new DataView(ihdr.buffer)
    view.setUint32(0, 3)
    view.setUint32(4, 2)
    ihdr[8] = 8
    ihdr[9] = 2
    return join(new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]),
        pngChunk('IHDR', ihdr), ...metadata,
        pngChunk('IDAT', zlibSync(new Uint8Array(20))), pngChunk('IEND', new Uint8Array()))
}

// A valid 3x2 lossy WebP, independently generated by libwebp.
const webp = new Uint8Array(Buffer.from('UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoDAAIAAUAmJaQAA3AA/v02aAA=', 'base64'))

function chunks(data: Uint8Array) {
    expect(new TextDecoder().decode(data.subarray(0, 4))).toBe('RIFF')
    expect(read32(data, 4)).toBe(data.length - 8)
    const result: Record<string, Uint8Array> = {}
    for (let offset = 12; offset < data.length;) {
        const name = new TextDecoder().decode(data.subarray(offset, offset + 4))
        const length = read32(data, offset + 4)
        result[name] = data.slice(offset + 8, offset + 8 + length)
        offset += 8 + length + (length % 2)
    }
    return result
}

// Read TIFF tags independently of the production writer, including its nested EXIF IFD.
function userComment(exif: Uint8Array) {
    const tiff = exif[0] === 69 ? exif.subarray(6) : exif
    const view = new DataView(tiff.buffer, tiff.byteOffset)
    const little = tiff[0] === 73
    const tags = (offset: number) => {
        const result = new Map<number, number>()
        const length = view.getUint16(offset, little)
        for (let n = 0; n < length; n++) result.set(view.getUint16(offset + 2 + n * 12, little), offset + 2 + n * 12)
        return result
    }
    const root = tags(view.getUint32(4, little))
    const exifPointer = root.get(0x8769)!
    const comment = tags(view.getUint32(exifPointer + 8, little)).get(0x9286)!
    const size = view.getUint32(comment + 4, little)
    const offset = view.getUint32(comment + 8, little)
    const payload = tiff.subarray(offset, offset + size)
    expect([...payload.subarray(0, 8)]).toEqual([85, 78, 73, 67, 79, 68, 69, 0])
    return new TextDecoder('utf-16be').decode(payload.subarray(8))
}

describe('BardPainter image metadata', () => {
    it('reads original PNG and converted WebP generation data for the gallery', () => {
        const source = png(pngChunk('iTXt', join(text('Comment'), new Uint8Array([0, 0, 0, 0, 0]), text('{"prompt":"blue cape","seed":42}'))))
        const metadata = readPainterImageMetadata(source)
        expect(metadata.Comment).toBe('{"prompt":"blue cape","seed":42}')
        expect(readPainterImageMetadata(muxPainterWebp(webp, preparePainterPng(source, {})))).toEqual(metadata)
        expect(readPainterImageMetadata(new Uint8Array([1, 2, 3]))).toEqual({})
        expect(readPainterImageMetadata(webp)).toEqual({})
    })
    it('carries NovelAI Unicode PNG metadata into a valid WebP EXIF UserComment', () => {
        const source = png(
            pngChunk('iTXt', join(text('Comment'), new Uint8Array([0, 0, 0, 0, 0]), text('{"prompt":"푸른 눈 🌊","seed":42}'))),
            pngChunk('tEXt', text('Software\0NovelAI')),
            pngChunk('tEXt', text('Generation_time\x001.4')),
        )
        const prepared = preparePainterPng(source, { seed: 99 })
        const output = chunks(muxPainterWebp(webp, prepared))
        expect(JSON.parse(userComment(output.EXIF))).toEqual({
            Comment: '{"prompt":"푸른 눈 🌊","seed":42}', Software: 'NovelAI', 'Generation time': '1.4',
        })
        expect(output.VP8X[0] & 0x08).toBe(0x08)
        expect(output['VP8 ']).toEqual(chunks(webp)['VP8 '])
    })

    it('keeps ICC bytes and compressed text while decoding without color-profile conversion', () => {
        const icc = new Uint8Array([1, 2, 3, 4, 5])
        const prepared = preparePainterPng(png(
            pngChunk('iCCP', join(text('profile'), new Uint8Array([0, 0]), zlibSync(icc))),
            pngChunk('zTXt', join(text('Description'), new Uint8Array([0, 0]), zlibSync(text('a red cape')))),
        ), { seed: 12 })
        const output = chunks(muxPainterWebp(webp, prepared))
        expect(output.ICCP).toEqual(icc)
        expect(output.VP8X[0] & 0x20).toBe(0x20)
        expect(JSON.parse(userComment(output.EXIF))).toMatchObject({ Description: 'a red cape', Comment: '{"seed":12}' })
        expect(new TextDecoder().decode(prepared.data)).not.toContain('iCCP')
    })

    it('uses actual request metadata when PNG has no generation text and excludes credentials', () => {
        const prepared = preparePainterPng(png(), {
            seed: 17, prompt: 'a quiet room', parameters: { scale: 6, apiKey: 'secret-key' }, authorization: 'secret-token',
        })
        const encoded = userComment(chunks(muxPainterWebp(webp, prepared)).EXIF)
        expect(JSON.parse(JSON.parse(encoded).Comment)).toEqual({ seed: 17, prompt: 'a quiet room', parameters: { scale: 6 } })
        expect(encoded).not.toContain('secret')
    })

    it('preserves existing EXIF UserComment without rewriting it', () => {
        const first = chunks(muxPainterWebp(webp, preparePainterPng(png(), { seed: 17 }))).EXIF
        const prepared = preparePainterPng(png(pngChunk('eXIf', first)), { seed: 99 })
        const second = chunks(muxPainterWebp(webp, prepared)).EXIF
        expect(second).toEqual(first)
        expect(JSON.parse(JSON.parse(userComment(second)).Comment).seed).toBe(17)
    })

    it('adds the comment without dropping existing orientation or changing the source', () => {
        // Little-endian TIFF, one SHORT Orientation tag with value 6, no EXIF IFD.
        const orientation = new Uint8Array([73, 73, 42, 0, 8, 0, 0, 0, 1, 0, 18, 1, 3, 0, 1, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0])
        const source = png(pngChunk('eXIf', orientation))
        const original = source.slice()
        const prepared = preparePainterPng(source, { seed: 13 })
        const exif = chunks(muxPainterWebp(webp, prepared)).EXIF
        const rootOffset = read32(exif, 4)
        expect([...exif.subarray(rootOffset + 2, rootOffset + 14)]).toEqual([...orientation.subarray(10, 22)])
        expect(JSON.parse(JSON.parse(userComment(exif)).Comment).seed).toBe(13)
        expect(source).toEqual(original)
    })

    it('reads compressed international text', () => {
        const prepared = preparePainterPng(png(pngChunk('iTXt', join(
            text('Description'), new Uint8Array([0, 1, 0, 0, 0]), zlibSync(text('붉은 망토')),
        ))), { seed: 12 })
        const output = chunks(muxPainterWebp(webp, prepared))
        expect(JSON.parse(userComment(output.EXIF)).Description).toBe('붉은 망토')
    })

    it.each([
        ['lossy', 'UklGRkYAAABXRUJQVlA4WAoAAAAQAAAAAgAAAQAAQUxQSAcAAAAAAAAAAAAAAFZQOCAYAAAAMAEAnQEqAwACAAFAJiWkAANwAP79NmgA'],
        ['lossless', 'UklGRhoAAABXRUJQVlA4TA0AAAAvAkAAEAcQERGIiP4HAA=='],
    ])('preserves transparency in %s WebP bitstreams', (_kind, fixture) => {
        const encoded = new Uint8Array(Buffer.from(fixture, 'base64'))
        const output = chunks(muxPainterWebp(encoded, preparePainterPng(png(), {})))
        expect(output.VP8X[0] & 0x10).toBe(0x10)
        const input = chunks(encoded)
        for (const kind of ['ALPH', 'VP8 ', 'VP8L']) expect(output[kind]).toEqual(input[kind])
    })

    it('rejects malformed source or encoder output instead of saving a mislabeled image', () => {
        expect(() => preparePainterPng(png().slice(0, 30), {})).toThrow()
        expect(() => muxPainterWebp(png(), preparePainterPng(png(), {}))).toThrow(/WebP/)
        expect(() => muxPainterWebp(webp, { ...preparePainterPng(png(), {}), width: 1 })).toThrow(/크기/)
    })
})

describe('BardPainter browser compression', () => {
    afterEach(() => {
        vi.restoreAllMocks()
        vi.unstubAllGlobals()
    })

    function browserEncoder(result: Uint8Array | null, decodeFails = false) {
        const createElement = document.createElement.bind(document)
        let canvas: HTMLCanvasElement
        vi.spyOn(document, 'createElement').mockImplementation((tag, options) => {
            const element = createElement(tag, options)
            if (tag === 'canvas') {
                canvas = element as HTMLCanvasElement
                canvas.getContext = (() => ({ drawImage() {} })) as unknown as typeof canvas.getContext
                canvas.toBlob = (callback, mime, quality) => {
                    if (mime !== 'image/webp' || quality !== 0.8 || canvas.width !== 3 || canvas.height !== 2) {
                        callback(null)
                        return
                    }
                    callback(result && new Blob([result.slice().buffer], { type: 'image/webp' }))
                }
            }
            return element
        })
        vi.stubGlobal('Image', class {
            naturalWidth = 3
            naturalHeight = 2
            onload: (() => void) | null = null
            onerror: (() => void) | null = null
            set src(value: string) {
                if (value) queueMicrotask(() => decodeFails ? this.onerror?.() : this.onload?.())
            }
        })
        const revoke = vi.spyOn(URL, 'revokeObjectURL')
        return { getCanvas: () => canvas, revoke }
    }

    it('rejects non-PNG data before attempting to decode it', async () => {
        await expect(compressPainterImage(new Uint8Array([1, 2, 3]), {})).rejects.toThrow(/PNG/)
    })

    it('returns original dimensions and portable metadata, then releases temporary image memory', async () => {
        const browser = browserEncoder(webp)
        const source = png()
        const original = source.slice()
        const compressed = await compressPainterImage(source, { seed: 42 })
        expect(compressed).toMatchObject({ width: 3, height: 2, mime: 'image/webp' })
        expect(JSON.parse(JSON.parse(userComment(chunks(compressed.data).EXIF)).Comment).seed).toBe(42)
        expect(source).toEqual(original)
        expect(browser.getCanvas().width).toBe(0)
        expect(browser.getCanvas().height).toBe(0)
        expect(browser.revoke).toHaveBeenCalledTimes(1)
    })

    it.each(['encode', 'decode'] as const)('releases temporary resources on %s failure without mutating the original', async (stage) => {
        const browser = browserEncoder(null, stage === 'decode')
        const source = png()
        const original = source.slice()
        await expect(compressPainterImage(source, {})).rejects.toThrow()
        expect(source).toEqual(original)
        expect(browser.getCanvas().width).toBe(0)
        expect(browser.revoke).toHaveBeenCalledTimes(1)
    })
})
